services:
  postgres:
    image: postgres:15-alpine
    container_name: deano-postgres
    environment:
      POSTGRES_DB: deano_task_manager
      POSTGRES_USER: deano
      POSTGRES_PASSWORD: deano_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deano -d deano_task_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    container_name: deano-api
    environment:
      DATABASE_URL: postgresql://deano:deano_password@postgres:5432/deano_task_manager
      NODE_ENV: production
      PORT: 3001
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      BYPASS_AUTH: false
      # Higher rate limits for development
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    container_name: deano-web
    environment:
      NEXT_PUBLIC_API_URL: http://api:3001
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
